language: node_js

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=altcatalin/jenkins-agent-amazonlinux2-nodejs

matrix:
  include:
    - node_js: 12

script:
  - export NODE_VERSION=$(node -e "console.log(process.version.match(/^v(\d+\.\d+\.\d+)/)[1])")
  - docker build --pull --tag "${IMAGE_NAME}":"${NODE_VERSION}" --build-arg NODE_VERSION="${NODE_VERSION}" .
  - docker run --entrypoint /usr/bin/cat "${IMAGE_NAME}":"${NODE_VERSION}" /etc/os-release | grep -i amazon
  - docker run --entrypoint node "${IMAGE_NAME}":"${NODE_VERSION}" --version | grep -i "${NODE_VERSION}"

after_script:
  - docker images

before_deploy:
  - docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASS}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${NODE_VERSION}"
  on:
    all_branches: true