os: linux
dist: xenial
language: node_js

services:
  - docker

env:
  global:
    - IMAGE_NAME=altcatalin/jenkins-agent-amazonlinux2-nodejs

jobs:
  include:
    - node_js: 12
    - node_js: 14

script:
  - docker build --pull --tag "${IMAGE_NAME}":"${TRAVIS_NODE_VERSION}" --build-arg NODE_VERSION="${TRAVIS_NODE_VERSION}" .
  - docker run --entrypoint /usr/bin/cat "${IMAGE_NAME}":"${TRAVIS_NODE_VERSION}" /etc/os-release | grep -i amazon
  - docker run --entrypoint node "${IMAGE_NAME}":"${TRAVIS_NODE_VERSION}" --version | grep -i "${TRAVIS_NODE_VERSION}"

after_script:
  - docker images

before_deploy:
  - docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASS}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TRAVIS_NODE_VERSION}"
  on:
    all_branches: true